apiVersion: v1
kind: Secret
metadata:
  name: rancher-uat-k8s-cluster2-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: argocd
type: Opaque
stringData:
  name: rancher-k8s-cluster2
  server: https://192.168.103.96/k8s/clusters/c-m-2mhmm77s
  config: |
    {
      "bearerToken": "token-knt6h:f2hvlrzk882zzvpr2snrjrpj8jdkl25w2kg9krk2sz8mvzkk9ggzjh",
      "tlsClientConfig": {
        "insecure": true
      }
    }
