# Default values for k10restore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

image:
  registry: gcr.io
  repository: kasten-images
  image: restorectl
  tag: ''
  pullPolicy: Always

airgapped:
    repository: ''

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# profileName has precedence over profile.name
# Added for the k10 Operator
# A non nested value allows for a cleaner k10restore form view
# Nested values are shown folded in a sub form
profileName:

profile:
  create: false
  name:

sourceClusterID:

skipResource:

pointInTime:

rbac:
  create: true

serviceAccount:
  create: true

secrets:
  awsIamRole: ''

scc:
  create: false

global:
  rhMarketPlace: false
  images:
    restorectl: ""

# similar to k10 support for Vault
vault:
  enabled: false
  role: ""
  serviceAccountTokenPath: ""
  address: ""
  secretName: ""

