apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redmine-share
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata/kubeapps-redmine-pvc"
    server: "192.168.103.146"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redmine
  namespace: kubeapps
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
