apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: garafana
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
spec:
    rules:
    - http:
        paths:
        - path: / 
          backend:
                serviceName: garafana
                servicePort: 80
           