apiVersion: v1
kind: Pod
metadata:
  name: rsapp
  labels:
    name: rsapp
spec:
  containers:
  - name: rsapp
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8085
