apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: kubeapps
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata"
    server: "192.168.104.3"