apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redmine
  namespace: kubeapps
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
