apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redmine
  namespace: kubeapps
spec:
  # storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi