apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-storage
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata/db"
    server: "192.168.103.146"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-storage
  namespace: db-storage
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi