apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db-storage
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata/db"
    server: "192.168.104.3"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db-storage
  namespace: kubeapps
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi