apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app-share
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata/pv-storage"
    server: "192.168.103.146"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app-share
  namespace: becamex-xlnt-dev
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi