{{- if .Values.ingress.enabled -}}
{{- $fullName := include "auth-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: traefik.containo.us/v1alpha1
{{- end }}
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "auth-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: {{ .Values.matchRule }}
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
  {{- end }}
