apiVersion: v2
description: pgAdmin is a web based administration tool for the PostgreSQL database.
home: https://www.pgadmin.org/
icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
keywords:
- pgadmin
- postgres
- database
- sql
maintainers:
- name: alexnuttinck
name: pgadmin
version: 0.1.12
