annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added option to add deployment extra volumes"
    - kind: added
      description: "Added option to template extraEnvs with helm tpl function"
    - kind: fixed
      description: "Fixed deployment args where all args were treated as a single arg"
  artifacthub.io/links: |
    - name: Camunda BPM Platform Chart
      url: https://github.com/camunda-community-hub/camunda-helm/tree/main/charts/camunda-bpm-platform
    - name: Camunda BPM Platform Docker
      url: https://github.com/camunda/docker-camunda-bpm-platform
    - name: Camunda BPM Platform
      url: https://github.com/camunda/camunda-bpm-platform
apiVersion: v2
appVersion: latest
description: 'Helm Chart for Camunda BPM Platform (Engines, Tasklist, Cockpit, etc). '
home: https://camunda.com
icon: https://docs.camunda.org/get-started/img/Camunda-Circle.svg
keywords:
- bpm
- bpmn
- camunda-bpm-platform
- camunda-engine
- dmn
- process-engine
- workflow
maintainers:
- name: aabouzaid
  url: https://tech.aabouzaid.com
name: camunda-bpm-platform
sources:
- https://github.com/camunda-community-hub/camunda-helm/tree/main/charts/camunda-bpm-platform
- https://github.com/camunda/docker-camunda-bpm-platform
- https://github.com/camunda/camunda-bpm-platform
type: application
version: 1.4.0
