apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-nginx
  namespace: nginx-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /$1 #set rewrite
spec:
  rules:
    # Tên miền truy cập
  - host: nginx-ingress.io
    http:
      paths:
      - path: /xxx
        backend:
          # dịch vụ phục vụ tương ứng với tên miền và path
          serviceName: http-test-svc
          servicePort: 80
      # - path: /auth
      #   backend:
      #     # dịch vụ phục vụ tương ứng với tên miền và path
      #     serviceName: auth-auth-api
      #     servicePort: 80      