
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata/minio"
    server: "192.168.103.146"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio
  namespace: kubeapps
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
