apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgadmin
  namespace: kubeapps
spec:
  storageClassName: nfs-minio-storage
  capacity:
    storage: 25Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/volume1/TRUNGTAMLUUTRU/Minio"
    server: "192.168.100.229"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio
  namespace: kubeapps
spec:
  storageClassName: nfs-minio-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
