apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: kubeapps
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:14
            command: ["/bin/sh", "-c"]
            args: 
              - '
                echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass
                echo start backuping ...
                pg_dump -U postgres -h postgres-postgresql --format=c bitnami_redmine > /var/backups/bitnami_redmine-$(date +"%d-%m-%Y");
                pg_dump -U postgres -h postgres-postgresql --format=c reminde_notify  > /var/backups/redmine_notify-$(date +"%d-%m-%Y");
                find /var/backups -mtime +30 -delete;
                echo done'
            env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: pgpass
                  key: pgpass
            volumeMounts:
            - mountPath: /var/backups
              name: postgres-backup
          restartPolicy: Never
          volumes:
          - name: postgres-backup
            persistentVolumeClaim:
              claimName: pvc-pg-backup
