apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: kubeapps
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgres-backup
            image: postgres:12
            command: ["/bin/sh"]
            args: ["-c", 'echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dump -U postgres -h postgres-postgres bitnami_redmine > /var/backups/bitnami_redmine-$(date +"%d-%m-%Y").sql']
            env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: pgpass
                  key: pgpass
            volumeMounts:
            - mountPath: /var/backups
              name: postgres-backup
          restartPolicy: Never
          volumes:
          - name: postgres-backup
            persistentVolumeClaim:
              claimName: pvc-pg-backup
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pg-backup
spec:
  storageClassName: nfs-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/srv/nfs/kubedata/kubeapps-postgresql-master/backup"
    server: "192.168.103.146"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pg-backup
  namespace: kubeapps
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
